[package]
name = "yy-boss"
version = "0.1.0"
authors = ["Jonathan Spira <jjspira@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2"
num-derive = "0.3"
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
serde_json = "1.0"
