[package]
name = "yy-boss"
version = "0.1.1"
authors = ["Jonathan Spira <jjspira@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A collection of typings and a higher-level interface for GameMaker Studio 2 YY and YYP files"
repository = "https://github.com/sanbox-irl/yy-boss"
readme = "README.md"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
serde_json = "1.0"
serde_repr = "0.1"
anyhow = "1.0"
smart-default = "0.6"
log = "0.4"
image = "0.23"
regex = "1.3"
strum = "0.18"
strum_macros = "0.18"

[dev-dependencies]
pretty_assertions = "0.6.1"
serde_json = "1.0"
